# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reasoning.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'reasoning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freasoning.proto\x12\treasoning\"<\n\nRunRequest\x12\x0f\n\x07program\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x0f\n\x07\x66n_name\x18\x03 \x01(\t\"D\n\tRunResult\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x06symbol\x18\x02 \x01(\tH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\x42\x08\n\x06resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reasoning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST']._serialized_start=30
  _globals['_RUNREQUEST']._serialized_end=90
  _globals['_RUNRESULT']._serialized_start=92
  _globals['_RUNRESULT']._serialized_end=160
# @@protoc_insertion_point(module_scope)

# ── CubbyLLM addition (not protoc output) ───────────────────────────────────
# `tests/test_guards.py::test_every_module_declares_wiring` imports every
# module under `cubbyllm` and requires `__wiring__`. protoc fully overwrites
# this file on regen, so re-append this block after regenerating the stub
# (see cubelang_client.py's module docstring for the regen command).
from ..core.protocols import Wiring  # noqa: E402

__wiring__ = Wiring.STANDALONE  # pure generated data schema, not a forward path
