# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reasoning.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reasoning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freasoning.proto\x12\treasoning\"\x88\x01\n\nRunRequest\x12\x0f\n\x07program\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x0f\n\x07\x66n_name\x18\x03 \x01(\t\x12\x0f\n\x07\x61nswers\x18\x04 \x03(\t\x12\x16\n\x0eknowledge_path\x18\x05 \x01(\t\x12!\n\x06\x62ranch\x18\x06 \x01(\x0b\x32\x11.reasoning.Branch\"H\n\x06\x42ranch\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x65xclude\x18\x02 \x03(\t\x12\x0e\n\x06\x61ssume\x18\x03 \x03(\t\x12\x11\n\tmax_jumps\x18\x04 \x01(\x04\"\xaf\x01\n\x0c\x42ranchReport\x12\x11\n\tbranch_id\x18\x01 \x01(\t\x12\x0b\n\x03ops\x18\x02 \x01(\x04\x12\r\n\x05jumps\x18\x03 \x01(\x04\x12#\n\x07queried\x18\x04 \x03(\x0b\x32\x12.reasoning.Queried\x12\x10\n\x08\x65xcluded\x18\x05 \x01(\r\x12\x0f\n\x07\x61ssumed\x18\x06 \x01(\r\x12\x15\n\rexcluded_keys\x18\x07 \x03(\t\x12\x11\n\tmax_jumps\x18\x08 \x01(\x04\"$\n\x07Queried\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04hits\x18\x02 \x01(\r\"T\n\tSuspended\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x12\n\ncandidates\x18\x02 \x03(\t\x12\x0f\n\x07program\x18\x03 \x01(\t\x12\x10\n\x08\x66unction\x18\x04 \x01(\t\"\xc0\x01\n\tRunResult\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x06symbol\x18\x02 \x01(\tH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\x12)\n\tsuspended\x18\x05 \x01(\x0b\x32\x14.reasoning.SuspendedH\x00\x12\x17\n\nsimilarity\x18\x04 \x01(\x01H\x01\x88\x01\x01\x12\'\n\x06report\x18\x06 \x01(\x0b\x32\x17.reasoning.BranchReportB\x08\n\x06resultB\r\n\x0b_similarityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reasoning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST']._serialized_start=31
  _globals['_RUNREQUEST']._serialized_end=167
  _globals['_BRANCH']._serialized_start=169
  _globals['_BRANCH']._serialized_end=241
  _globals['_BRANCHREPORT']._serialized_start=244
  _globals['_BRANCHREPORT']._serialized_end=419
  _globals['_QUERIED']._serialized_start=421
  _globals['_QUERIED']._serialized_end=457
  _globals['_SUSPENDED']._serialized_start=459
  _globals['_SUSPENDED']._serialized_end=543
  _globals['_RUNRESULT']._serialized_start=546
  _globals['_RUNRESULT']._serialized_end=738
# @@protoc_insertion_point(module_scope)
